[package]
name = "part3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
petgraph = "0.6.4"
csv = "1.1"

[profile.release]
opt-level = 3
